version: '3'

services:
  api:
    container_name: ng-cash
    image: node:18-alpine3.14
    restart: 'always'
    tty: true
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/src/app
    environment:
      - PORT=3000
  db:
    container_name: ng-cash-database
    image: postgres:latest
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ng-challenge
  rabbitmq:
    hostname: rabbitmq-container
    image: rabbitmq:3.7-management
    container_name: ng-cash-rabbitmq
    build: ./dockerfile-rmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - type: bind
        source: ./dockerfile-rmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./dockerfile-rmq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./dockerfile-rmq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json

networks:
  default:
    external:
      name: ng-cash-network
